In [5]:
import pandas as pd
data = [[1,'a',1.2],[2,'b',2.2],[3,'c',3.2]]
df = pd.DataFrame(data = data,
                  index = ['row_%d'%i for i in range(3)],
                  columns=['col_0','col_1','col_2'])
df

       col_0 col_1  col_2
row_0      1     a    1.2
row_1      2     b    2.2
row_2      3     c    3.2

In [18]:
df = pd.DataFrame(data = {'col_0':[1,2,3],'col_1':list('abc'),
                          'col_2':[1.2,2.2,3.2]},
                  index = ['row_%d'%i for i in range(3)])
print(df)
print(df['col_0'])
print(df[['col_0','col_1']])
print(df.values)
print(df.index)
print(df.columns)
print(df.dtypes)
print(df.shape)
print(df.T)

       col_0 col_1  col_2
row_0      1     a    1.2
row_1      2     b    2.2
row_2      3     c    3.2
row_0    1
row_1    2
row_2    3
Name: col_0, dtype: int64
       col_0 col_1
row_0      1     a
row_1      2     b
row_2      3     c
[[1 'a' 1.2]
 [2 'b' 2.2]
 [3 'c' 3.2]]
Index(['row_0', 'row_1', 'row_2'], dtype='str')
Index(['col_0', 'col_1', 'col_2'], dtype='str')
col_0      int64
col_1        str
col_2    float64
dtype: object
(3, 3)
      row_0 row_1 row_2
col_0     1     2     3
col_1     a     b     c
col_2   1.2   2.2   3.2

In [25]:
import pandas as pd
df = pd.read_csv('data/learn_pandas.csv')
print(df.columns)
df = df[df.columns[:7]]
print(df)
print(df.head(2))
print(df.tail(3))

Index(['School', 'Grade', 'Name', 'Gender', 'Height', 'Weight', 'Transfer',
       'Test_Number', 'Test_Date', 'Time_Record'],
      dtype='str')
    School      Grade            Name  Gender  Height  Weight Transfer
0        A   Freshman    Gaopeng Yang  Female   158.9    46.0        N
1        B   Freshman  Changqiang You    Male   166.5    70.0        N
2        A     Senior         Mei Sun    Male   188.9    89.0        N
3        C  Sophomore    Xiaojuan Sun  Female     NaN    41.0        N
4        C  Sophomore     Gaojuan You    Male   174.0    74.0        N
..     ...        ...             ...     ...     ...     ...      ...
195      C     Junior    Xiaojuan Sun  Female   153.9    46.0        N
196      D     Senior         Li Zhao  Female   160.9    50.0        N
197      A     Senior  Chengqiang Chu  Female   153.9    45.0        N
198      A     Senior   Chengmei Shen    Male   175.3    71.0        N
199      D  Sophomore     Chunpeng Lv    Male   155.7    51.0        N

[200 rows x 7 columns]
  School     Grade            Name  Gender  Height  Weight Transfer
0      A  Freshman    Gaopeng Yang  Female   158.9    46.0        N
1      B  Freshman  Changqiang You    Male   166.5    70.0        N
    School      Grade            Name  Gender  Height  Weight Transfer
197      A     Senior  Chengqiang Chu  Female   153.9    45.0        N
198      A     Senior   Chengmei Shen    Male   175.3    71.0        N
199      D  Sophomore     Chunpeng Lv    Male   155.7    51.0        N

In [29]:
print(df.info())
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   School    200 non-null    str
 1   Grade     200 non-null    str
 2   Name      200 non-null    str
 3   Gender    200 non-null    str
 4   Height    183 non-null    float64
 5   Weight    189 non-null    float64
 6   Transfer  188 non-null    str
dtypes: float64(2), str(5)
memory usage: 16.0 KB
None

           Height      Weight
count  183.000000  189.000000
mean   163.218033   55.015873
std      8.608879   12.824294
min    145.400000   34.000000
25%    157.150000   46.000000
50%    161.900000   51.000000
75%    167.500000   65.000000
max    193.900000   89.000000

In [ ]:
df_demo = df[['Height','Weight']]
print(df_demo.mean())
print(df_demo.max())
print(df_demo.quantile(0.75))
print(df_demo.count())
print(df_demo.idxmax())
print(df_demo.mean(axis=1).head())

Height    163.218033
Weight     55.015873
dtype: float64
Height    193.9
Weight     89.0
dtype: float64
Height    167.5
Weight     65.0
Name: 0.75, dtype: float64
Height    183
Weight    189
dtype: int64
Height    193
Weight      2
dtype: int64
0    102.45
1    118.25
2    138.95
3     41.00
4    124.00
dtype: float64

<ArrowStringArray>
['A', 'B', 'C', 'D']
Length: 4, dtype: str

In [46]:
import pandas as pd
df = pd.read_csv('data/learn_pandas.csv')
print(df['School'].unique())
print(df['School'].nunique())
print(df['School'].value_counts())
df_demo = df[['Gender','Transfer','Name']]
print(df_demo)
print(df_demo.drop_duplicates(['Gender','Transfer']))
df_demo.drop_duplicates(['Gender','Transfer'],keep='last')

<ArrowStringArray>
['A', 'B', 'C', 'D']
Length: 4, dtype: str
4
School
D    69
A    57
C    40
B    34
Name: count, dtype: int64
     Gender Transfer            Name
0    Female        N    Gaopeng Yang
1      Male        N  Changqiang You
2      Male        N         Mei Sun
3    Female        N    Xiaojuan Sun
4      Male        N     Gaojuan You
..      ...      ...             ...
195  Female        N    Xiaojuan Sun
196  Female        N         Li Zhao
197  Female        N  Chengqiang Chu
198    Male        N   Chengmei Shen
199    Male        N     Chunpeng Lv

[200 rows x 3 columns]
    Gender Transfer            Name
0   Female        N    Gaopeng Yang
1     Male        N  Changqiang You
12  Female      NaN        Peng You
21    Male      NaN   Xiaopeng Shen
36    Male        Y    Xiaojuan Qin
43  Female        Y      Gaoli Feng

     Gender Transfer            Name
147    Male      NaN        Juan You
150    Male        Y   Chengpeng You
169  Female        Y   Chengquan Qin
194  Female      NaN     Yanmei Qian
197  Female        N  Chengqiang Chu
199    Male        N     Chunpeng Lv

In [53]:
print(df_demo.drop_duplicates(['Name','Gender'],keep=False).head())
print(df['School'].drop_duplicates())
print(df_demo.duplicated(['Gender','Transfer']).head())
print(df['School'].duplicated().head())

   Gender Transfer            Name
0  Female        N    Gaopeng Yang
1    Male        N  Changqiang You
2    Male        N         Mei Sun
4    Male        N     Gaojuan You
5  Female        N     Xiaoli Qian
0    A
1    B
3    C
5    D
Name: School, dtype: str
0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3    False
4     True
Name: School, dtype: bool

In [62]:
print(df['Gender'].replace({'Female':0,'Male':1}).head())
print(df['Gender'].replace(['Female','Male'],[0,1]).head())

0    0
1    1
2    1
3    0
4    1
Name: Gender, dtype: object
0    0
1    1
2    1
3    0
4    1
Name: Gender, dtype: object

In [70]:
s = pd.Series([-1,1.2345,100,-50])
print(s.where(s<0))
print(s.where(s<0,100))
print(s.mask(s<0))
print(s.mask(s<0,-50))
s_condition=pd.Series([True,False,False,True],index=s.index)
print(s.mask(s_condition,-50))

0    -1.0
1     NaN
2     NaN
3   -50.0
dtype: float64
0     -1.0
1    100.0
2    100.0
3    -50.0
dtype: float64
0         NaN
1      1.2345
2    100.0000
3         NaN
dtype: float64
0    -50.0000
1      1.2345
2    100.0000
3    -50.0000
dtype: float64
0    -50.0000
1      1.2345
2    100.0000
3    -50.0000
dtype: float64

In [85]:
s = pd.Series([-1,1.2345,100,-50])
print(s.round(2))
print(s.abs())
print(s.clip(0,2))

0     -1.00
1      1.23
2    100.00
3    -50.00
dtype: float64
0      1.0000
1      1.2345
2    100.0000
3     50.0000
dtype: float64
0    0.0000
1    1.2345
2    2.0000
3    0.0000
dtype: float64

In [88]:
import pandas as pd
import numpy as np
s = pd.Series([-10,0,50,100,150])
lower,upper=0,100
result = pd.Series(
    np.select([s < lower,s > upper],[-1,999],default=s),
    index=s.index
)
print(result)

0     -1
1      0
2     50
3    100
4    999
dtype: int64